export const States = [
  { id: 1, state: "Abia" },
  { id: 2, state: "Adamawa" },
  { id: 3, state: "Akwa Ibom" },
  { id: 4, state: "Anambra" },
  { id: 5, state: "Bauchi" },
  { id: 6, state: "Bayelsa" },
  { id: 7, state: "Benue" },
  { id: 8, state: "Borno" },
  { id: 9, state: "Cross River" },
  { id: 10, state: "Delta" },
  { id: 11, state: "Ebonyi" },
  { id: 12, state: "Edo" },
  { id: 13, state: "Ekiti" },
  { id: 14, state: "Enugu" },
  { id: 15, state: "FCT" },
  { id: 16, state: "Gombe" },
  { id: 17, state: "Imo" },
  { id: 18, state: "Jigawa" },
  { id: 19, state: "Kaduna" },
  { id: 20, state: "Kano" },
  { id: 21, state: "Katsina" },
  { id: 22, state: "Kebbi" },
  { id: 23, state: "Kogi" },
  { id: 24, state: "Kwara" },
  { id: 25, state: "Lagos" },
  { id: 26, state: "Nasarawa" },
  { id: 27, state: "Niger" },
  { id: 28, state: "Ogun" },
  { id: 29, state: "Ondo" },
  { id: 30, state: "Osun" },
  { id: 31, state: "Oyo" },
  { id: 32, state: "Plateau" },
  { id: 33, state: "Rivers" },
  { id: 34, state: "Sokoto" },
  { id: 35, state: "Taraba" },
  { id: 36, state: "Yobe" },
  { id: 37, state: "Zamfara" },
  { id: 38, state: "Outside Nigeria" },
];
